# Generated by Django 4.2.28 on 2026-06-29 17:13

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='status',
            field=models.ForeignKey(default=course.models.get_default_status, on_delete=django.db.models.deletion.PROTECT, to='course.status'),
        ),
    ]
